### ISSUE TITLE
报告weex-vue-render 0.11.2 版本的几个bug

### ISSUE THREAD

**Issue by segatecm** [MrRaindrop/weex#15]
以下问题都是h5版本问题：
1.在ios手机浏览器里面运行的时候，slider的图片有时候不显示，需要等到第一次滑动结束后，图片才显示。
2.slider里面的indicator不能使用，颜色位置都不受代码控制。
3.body不知道为什么多了margin：8px。
4.在使用loading功能的时候，scroller的性能表现太差，动态加载了20多条数据后就卡顿得无法滑动。
5.在使用loading方式动态加载内容的时候，如果其中有image的内容，并且image在屏幕中出现的时候，它的图片不会显示。

希望能尽快修复这些bug，因为在项目中急用。

**Comment by MrRaindrop** [comment]
更新一下版本到 0.11.x 试试

**Comment by MrRaindrop** [comment]
能否每个 bug 给个 demo. 目前你说的问题大部分在 0.11.2 上我都没有复现出来。确认一下，你的 console 里是否出现了 `START WEEX VUE RENDER: 0.11.2, Build 2017-03-28 15:22.`  的 log ?

**Comment by segatecm** [comment]
嗯，你能给个联系方式吗？给个微信联系方式吧。我可以把h5的页面地址发给你看。
